### Add New Synopsis local

POST http://localhost:7071/api/add-new

{
    "shortdescription": "This is a test again",
    "submitteremail": "lbugnion@microsoft.com",
    "submittername": "Laurent Bugnion",
    "submittertwitter": "@LBugnion",
    "submittergithub": "LBugnion",
    "topic":"test-topic-07"
}

### Update Homepage local
http://localhost:7071/api/UpdateHomePage