### Add New Synopsis local
POST http://localhost:7071/api/add-new

{
    "shortdescription": "This is a test again",
    "submitteremail": "lbugnion@microsoft.com",
    "submittername": "Laurent Bugnion",
    "submittertwitter": "@LBugnion",
    "submittergithub": "LBugnion",
    "term":"test-topic-11"
}

### Add New Synopsis Staging
POST https://msglossary-app-staging.azurewebsites.net/api/add-new
x-functions-key: OTQgPYaBCra07bwwQT4TtoTa6hP26oWm1jHoCJg2UiJjV8RRWoOMIw==

{
    "shortdescription": "This is a test again",
    "submitteremail": "lbugnion@microsoft.com",
    "submittername": "Laurent Bugnion",
    "submittertwitter": "@LBugnion",
    "submittergithub": "LBugnion",
    "term":"test-topic-11"
}

### Update Homepage local
http://localhost:7071/api/UpdateHomePage

### Update Docs
https://msglossary-app.azurewebsites.net/api/update-docs
x-functions-key: djXnjM/5wuUarZcaxmvj84bt0WGOH6g10G3PtJxpVmCFiKVsqlNm2A==

### Update Docs local
http://localhost:7071/api/update-docs

### Update Docs Staging
https://msglossary-app-staging.azurewebsites.net/api/update-docs
x-functions-key: Xq9pl6xS6uI1RVuxKaN0e2HG6ts0AKgqAbniQQXKUCaHxDEAdtC1Fw==

### Get synopsis for edit
http://localhost:7071/api/synopsis

{
    "submitteremail": "lbugnion2@microsoft.com",
    "term":"test-topic-11"
}
