//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsOfTheDayApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordsOfTheDayApp.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string en_By {
            get {
                return ResourceManager.GetString("en.By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Copyright {0} by Microsoft Azure Words of the Day - [Contact us]({1})*.
        /// </summary>
        internal static string en_CopyrightInfo {
            get {
                return ResourceManager.GetString("en.CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### `{0}` can be used in different contexts:.
        /// </summary>
        internal static string en_DisambiguationIntro {
            get {
                return ResourceManager.GetString("en.DisambiguationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - In [{0}](/topic/{1}/{2}_{3}), {4}.
        /// </summary>
        internal static string en_DisambiguationItem {
            get {
                return ResourceManager.GetString("en.DisambiguationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # [{0}](/topic/{1}/{2}) (disambiguation).
        /// </summary>
        internal static string en_DisambiguationTitle {
            get {
                return ResourceManager.GetString("en.DisambiguationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Last modified: {0}*.
        /// </summary>
        internal static string en_LastModified {
            get {
                return ResourceManager.GetString("en.LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected from {0}.
        /// </summary>
        internal static string en_RedirectedFrom {
            get {
                return ResourceManager.GetString("en.RedirectedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is also available in:.
        /// </summary>
        internal static string en_ThisPageIsAlsoAvailableIn {
            get {
                return ResourceManager.GetString("en.ThisPageIsAlsoAvailableIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Microsoft Azure Words of the Day presents:.
        /// </summary>
        internal static string en_TopicHeader {
            get {
                return ResourceManager.GetString("en.TopicHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/AzWordsOfTheDay.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngo.
        /// </summary>
        internal static string zu_By {
            get {
                return ResourceManager.GetString("zu.By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *I-copyright {0} ka - [Xhumana nathi]({1})*.
        /// </summary>
        internal static string zu_CopyrightInfo {
            get {
                return ResourceManager.GetString("zu.CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### `{0}` ingasetshenziswa ezimeni ezahlukahlukene:.
        /// </summary>
        internal static string zu_DisambiguationIntro {
            get {
                return ResourceManager.GetString("zu.DisambiguationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - In [{0}](/topic/{1}/{2}_{3}), {4}.
        /// </summary>
        internal static string zu_DisambiguationItem {
            get {
                return ResourceManager.GetString("zu.DisambiguationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # [{0}](/topic/{1}/{2}) (ukudideka).
        /// </summary>
        internal static string zu_DisambiguationTitle {
            get {
                return ResourceManager.GetString("zu.DisambiguationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Kugcine ukuguqulwa: {0}*.
        /// </summary>
        internal static string zu_LastModified {
            get {
                return ResourceManager.GetString("zu.LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuqondiswe kabusha kusuka {0}.
        /// </summary>
        internal static string zu_RedirectedFrom {
            get {
                return ResourceManager.GetString("zu.RedirectedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leli khasi liyatholakala naku:.
        /// </summary>
        internal static string zu_ThisPageIsAlsoAvailableIn {
            get {
                return ResourceManager.GetString("zu.ThisPageIsAlsoAvailableIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Microsoft Azure Amagama wosuku izipho:.
        /// </summary>
        internal static string zu_TopicHeader {
            get {
                return ResourceManager.GetString("zu.TopicHeader", resourceCulture);
            }
        }
    }
}
