//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsGlossaryApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsGlossaryApp.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string en_TermAuthors {
            get {
                return ResourceManager.GetString("en.TermAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are captions for the following language(s):.
        /// </summary>
        internal static string en_TermCaptions {
            get {
                return ResourceManager.GetString("en.TermCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about [downloading and showing captions here].
        /// </summary>
        internal static string en_TermCaptionsLearn {
            get {
                return ResourceManager.GetString("en.TermCaptionsLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page was created by.
        /// </summary>
        internal static string en_TermCreatedBy {
            get {
                return ResourceManager.GetString("en.TermCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string en_TermDefinition {
            get {
                return ResourceManager.GetString("en.TermDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Glossary definition for {0}.
        /// </summary>
        internal static string en_TermDescription {
            get {
                return ResourceManager.GetString("en.TermDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Glossary disambiguation for {0}.
        /// </summary>
        internal static string en_TermDescriptionDisambiguation {
            get {
                return ResourceManager.GetString("en.TermDescriptionDisambiguation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` can be used in different contexts.
        /// </summary>
        internal static string en_TermDifferentContexts {
            get {
                return ResourceManager.GetString("en.TermDifferentContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disambiguation.
        /// </summary>
        internal static string en_TermDisambiguation {
            get {
                return ResourceManager.GetString("en.TermDisambiguation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string en_TermDownload {
            get {
                return ResourceManager.GetString("en.TermDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download this video here.
        /// </summary>
        internal static string en_TermDownloadHere {
            get {
                return ResourceManager.GetString("en.TermDownloadHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - In {0}, {1}.
        /// </summary>
        internal static string en_TermIn {
            get {
                return ResourceManager.GetString("en.TermIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string en_TermLanguages {
            get {
                return ResourceManager.GetString("en.TermLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string en_TermLinks {
            get {
                return ResourceManager.GetString("en.TermLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-product-specific.
        /// </summary>
        internal static string en_TermNonProductSpecific {
            get {
                return ResourceManager.GetString("en.TermNonProductSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random term for today.
        /// </summary>
        internal static string en_TermRandomTerm {
            get {
                return ResourceManager.GetString("en.TermRandomTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirected from {0}.
        /// </summary>
        internal static string en_TermRedirectedFrom {
            get {
                return ResourceManager.GetString("en.TermRedirectedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Glossary.
        /// </summary>
        internal static string en_TermTocTitle {
            get {
                return ResourceManager.GetString("en.TermTocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript.
        /// </summary>
        internal static string en_TermTranscript {
            get {
                return ResourceManager.GetString("en.TermTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/AzWordsOfTheDay.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
    }
}
