//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsGlossaryApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsGlossaryApp.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string en_TopicAuthors {
            get {
                return ResourceManager.GetString("en.TopicAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are captions for the following language(s):.
        /// </summary>
        internal static string en_TopicCaptions {
            get {
                return ResourceManager.GetString("en.TopicCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about [downloading and showing captions here].
        /// </summary>
        internal static string en_TopicCaptionsLearn {
            get {
                return ResourceManager.GetString("en.TopicCaptionsLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This topic was created by.
        /// </summary>
        internal static string en_TopicCreatedBy {
            get {
                return ResourceManager.GetString("en.TopicCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string en_TopicDefinition {
            get {
                return ResourceManager.GetString("en.TopicDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Glossary definition for {0}.
        /// </summary>
        internal static string en_TopicDescription {
            get {
                return ResourceManager.GetString("en.TopicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Glossary disambiguation for {0}.
        /// </summary>
        internal static string en_TopicDescriptionDisambiguation {
            get {
                return ResourceManager.GetString("en.TopicDescriptionDisambiguation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}` can be used in different contexts.
        /// </summary>
        internal static string en_TopicDifferentContexts {
            get {
                return ResourceManager.GetString("en.TopicDifferentContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disambiguation.
        /// </summary>
        internal static string en_TopicDisambiguation {
            get {
                return ResourceManager.GetString("en.TopicDisambiguation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string en_TopicDownload {
            get {
                return ResourceManager.GetString("en.TopicDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download this video here.
        /// </summary>
        internal static string en_TopicDownloadHere {
            get {
                return ResourceManager.GetString("en.TopicDownloadHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - In {0}, {1}.
        /// </summary>
        internal static string en_TopicIn {
            get {
                return ResourceManager.GetString("en.TopicIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string en_TopicLanguages {
            get {
                return ResourceManager.GetString("en.TopicLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string en_TopicLinks {
            get {
                return ResourceManager.GetString("en.TopicLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-product-specific.
        /// </summary>
        internal static string en_TopicNonProductSpecific {
            get {
                return ResourceManager.GetString("en.TopicNonProductSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random topic for today.
        /// </summary>
        internal static string en_TopicRandomTopic {
            get {
                return ResourceManager.GetString("en.TopicRandomTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirected from {0}.
        /// </summary>
        internal static string en_TopicRedirectedFrom {
            get {
                return ResourceManager.GetString("en.TopicRedirectedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Glossary.
        /// </summary>
        internal static string en_TopicTocTitle {
            get {
                return ResourceManager.GetString("en.TopicTocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript.
        /// </summary>
        internal static string en_TopicTranscript {
            get {
                return ResourceManager.GetString("en.TopicTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/AzWordsOfTheDay.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
    }
}
