# When executed, this workflow creates the Release notes for this project

name: Create Release notes

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, deleted, transferred, closed, reopened, labeled, milestoned, demilestoned]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
        with:
          url: https://msglossary-app.azurewebsites.net/api/release-notes/milestones/all
          method: get
          headers: '{ "x-functions-key": "${{ secrets.ReleaseNotesFunctionKey }}" }'
