# When executed, this workflow creates the Release notes for this project

name: Create Release notes

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
        with:
          url: https://release-notes-maker.azurewebsites.net/api/release-notes/milestones/all
          method: post
          headers: '{ "x-functions-key": "${{ secrets.ReleaseNotesFunctionKey }}", "x-releasenotesmaker-token": "${{ secrets.ReleaseNotesGitHubToken }}" }'
          data: '{"AccountName": "lbugnion","RepoName": "ms-glossary-app","BranchName": "main","CommitMessage": "Updated release notes","SinglePage": false,"Projects": [{"Project": "Infrastructure","ProjectId": 4},{"Project": "Backend Functions","ProjectId": 2},{"Project": "Synopsis Client","ProjectId": 1},{"Project": "Microsoft Glossary App","IsMainPage": true}]}'
